import type { Metadata } from "next";
import { Inter, Jost, Noto_Sans, Noto_Sans_Bengali } from "next/font/google";
import { getLocale } from "next-intl/server";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-inter",
  display: "swap",
});

// Jost — the closest open substitute for Nike Futura ND. Used only by
// `.text-display-campaign` for uppercase campaign headlines (DESIGN.md,
// "Note on Font Substitutes"). Latin-only: Bangla headlines fall through
// to Noto Sans Bengali via --font-display.
const jost = Jost({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  variable: "--font-jost",
  display: "swap",
});

// Noto Sans — fallback for Latin characters (lower-priority than Inter).
const noto = Noto_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-noto",
  display: "swap",
});

// Bangla glyphs for the /bn locale — falls into the font stack after Inter
// and Noto Sans, so Latin text keeps Inter's metrics while Bengali stays crisp.
const notoBengali = Noto_Sans_Bengali({
  subsets: ["bengali"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-noto-bengali",
  display: "swap",
});

const SITE_URL = "https://thriftedbd.com";
const SITE_NAME = "thriftedBD";
const SITE_DESCRIPTION =
  "Quality-checked, imported thrifted fashion from Korea, Japan, Taiwan & China. Cash on delivery across Bangladesh.";

export const metadata: Metadata = {
  // Resolves relative OG/canonical URLs (incl. the app/opengraph-image and
  // app/icon file-convention assets) against the production origin.
  metadataBase: new URL(SITE_URL),
  title: {
    // Per-route generateMetadata() titles slot into the template; the home
    // page and any route without its own title fall back to `default`.
    default: "thriftedBD — Imported preloved fashion",
    template: "%s | thriftedBD",
  },
  description: SITE_DESCRIPTION,
  applicationName: SITE_NAME,
  keywords: [
    "thrift Bangladesh",
    "thrifted clothing",
    "secondhand fashion Dhaka",
    "preloved clothes BD",
    "imported thrift",
    "cash on delivery fashion",
  ],
  authors: [{ name: SITE_NAME, url: SITE_URL }],
  creator: SITE_NAME,
  publisher: SITE_NAME,
  category: "shopping",
  alternates: {
    canonical: "/",
  },
  openGraph: {
    type: "website",
    siteName: SITE_NAME,
    title: "thriftedBD — Imported preloved fashion",
    description: SITE_DESCRIPTION,
    url: SITE_URL,
    locale: "en_US",
    // Image + alt are generated by src/app/opengraph-image.tsx.
  },
  twitter: {
    card: "summary_large_image",
    title: "thriftedBD — Imported preloved fashion",
    description: SITE_DESCRIPTION,
    // Image + alt are generated by src/app/twitter-image.tsx.
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  // The full favicon set lives in /public/icons. The legacy /favicon.ico route
  // is served from the app/favicon.ico file convention; these explicit links
  // add the PNG + Apple-touch variants. PWA icons come from the web manifest.
  icons: {
    icon: [
      { url: "/icons/favicon-32x32.png", sizes: "32x32", type: "image/png" },
      { url: "/icons/favicon-16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/icons/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
    apple: [{ url: "/icons/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
  },
};

const organizationJsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "@id": `${SITE_URL}/#organization`,
      name: SITE_NAME,
      url: SITE_URL,
      logo: {
        "@type": "ImageObject",
        "@id": `${SITE_URL}/#logo`,
        url: `${SITE_URL}/logos/logo.png`,
        width: 669,
        height: 373,
        caption: SITE_NAME,
      },
      image: `${SITE_URL}/opengraph-image`,
      description:
        "Online thrifted/secondhand clothing platform in Bangladesh. Quality-checked preloved fashion imported from Korea, Japan, Taiwan & China.",
    },
    {
      "@type": "WebSite",
      "@id": `${SITE_URL}/#website`,
      url: SITE_URL,
      name: SITE_NAME,
      description: SITE_DESCRIPTION,
      inLanguage: "en",
      publisher: { "@id": `${SITE_URL}/#organization` },
    },
  ],
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Resolved from the URL by next-intl; admin routes (outside the [locale]
  // segment) fall back to "en".
  const locale = await getLocale();
  return (
    <html
      lang={locale}
      className={`${inter.variable} ${jost.variable} ${noto.variable} ${notoBengali.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationJsonLd) }}
        />
        {children}
      </body>
    </html>
  );
}
