/**
 * thriftedBD — Dummy Data for All Collections
 *
 * Replace `https://placehold.co/...` image URLs with real R2 URLs when you
 * have the images. The placeholder size is 600×800 (portrait for clothing).
 *
 * ID strings (e.g. "cat-men", "color-black") are readable cross-references,
 * NOT real MongoDB ObjectIds. When seeding, either:
 *   a) Insert in dependency order and capture real _ids, or
 *   b) Replace them with hard-coded ObjectId hex strings.
 */

// ─── Helpers ───────────────────────────────────────────────────────────────

interface I18n {
  en: string;
  bn?: string;
}

function i18n(en: string, bn?: string): I18n {
  return { en, bn };
}

// ─── 1. Owners ─────────────────────────────────────────────────────────────
// Who physically holds the inventory.

export const owners = [
  { _id: "owner-me", name: "Saif", phone: "01711111111", isActive: true },
  { _id: "owner-shaikh", name: "Shaikh", phone: "01722222222", isActive: true },
  { _id: "owner-rahim", name: "Rahim", phone: "01733333333", isActive: true },
];

// ─── 2. Colors ─────────────────────────────────────────────────────────────

export const colors = [
  { _id: "color-black", name: i18n("Black", "কালো"), hex: "#000000" },
  { _id: "color-white", name: i18n("White", "সাদা"), hex: "#FFFFFF" },
  { _id: "color-navy", name: i18n("Navy", "নেভি ব্লু"), hex: "#000080" },
  { _id: "color-gray", name: i18n("Gray", "ধূসর"), hex: "#808080" },
  { _id: "color-beige", name: i18n("Beige", "বেইজ"), hex: "#F5F5DC" },
  { _id: "color-brown", name: i18n("Brown", "বাদামী"), hex: "#A52A2A" },
  { _id: "color-green", name: i18n("Green", "সবুজ"), hex: "#008000" },
  { _id: "color-olive", name: i18n("Olive", "অলিভ"), hex: "#556B2F" },
  { _id: "color-blue", name: i18n("Blue", "নীল"), hex: "#0000FF" },
  { _id: "color-light-blue", name: i18n("Light Blue", "হালকা নীল"), hex: "#ADD8E6" },
  { _id: "color-red", name: i18n("Red", "লাল"), hex: "#FF0000" },
  { _id: "color-maroon", name: i18n("Maroon", "মেরুন"), hex: "#800000" },
  { _id: "color-pink", name: i18n("Pink", "গোলাপী"), hex: "#FFC0CB" },
  { _id: "color-mustard", name: i18n("Mustard", "সরিষে হলুদ"), hex: "#FFDB58" },
  { _id: "color-purple", name: i18n("Purple", "বেগুনী"), hex: "#800080" },
  { _id: "color-cream", name: i18n("Cream", "ক্রিম"), hex: "#FFFDD0" },
  { _id: "color-coral", name: i18n("Coral", "কোরাল"), hex: "#FF7F50" },
  { _id: "color-teal", name: i18n("Teal", "টিাল"), hex: "#008080" },
  { _id: "color-khaki", name: i18n("Khaki", "খাকি"), hex: "#C3B091" },
  { _id: "color-denim", name: i18n("Denim", "ডেনিম"), hex: "#1565C0" },
];

// ─── 3. Categories — Department / Category tree ────────────────────────────

export const categories = [
  // ── Departments (level 0) ──
  {
    _id: "cat-men",
    name: i18n("Men", "পুরুষ"),
    slug: "men",
    parentId: null,
    level: 0,
    order: 1,
    isActive: true,
  },
  {
    _id: "cat-women",
    name: i18n("Women", "মহিলা"),
    slug: "women",
    parentId: null,
    level: 0,
    order: 2,
    isActive: true,
  },
  {
    _id: "cat-bags",
    name: i18n("Bags", "ব্যাগ"),
    slug: "bags",
    parentId: null,
    level: 0,
    order: 3,
    isActive: true,
  },
  {
    _id: "cat-household",
    name: i18n("Household", "গৃহস্থালী"),
    slug: "household",
    parentId: null,
    level: 0,
    order: 4,
    isActive: true,
  },
  {
    _id: "cat-kids",
    name: i18n("Baby & Kids", "শিশু ও বাচ্চা"),
    slug: "baby-kids",
    parentId: null,
    level: 0,
    order: 5,
    isActive: true,
  },

  // ── Men categories (level 1) ──
  {
    _id: "cat-men-tshirt",
    name: i18n("T-Shirts", "টি-শার্ট"),
    slug: "t-shirts",
    parentId: "cat-men",
    level: 1,
    order: 1,
    isActive: true,
  },
  {
    _id: "cat-men-shirt",
    name: i18n("Shirts", "শার্ট"),
    slug: "shirts",
    parentId: "cat-men",
    level: 1,
    order: 2,
    isActive: true,
  },
  {
    _id: "cat-men-trouser",
    name: i18n("Trousers", "ট্রাউজার"),
    slug: "trousers",
    parentId: "cat-men",
    level: 1,
    order: 3,
    isActive: true,
  },
  {
    _id: "cat-men-hoodie",
    name: i18n("Hoodies & Sweatshirts", "হুডি ও সোয়েটশার্ট"),
    slug: "hoodies-sweatshirts",
    parentId: "cat-men",
    level: 1,
    order: 4,
    isActive: true,
  },
  {
    _id: "cat-men-jacket",
    name: i18n("Jackets & Outerwear", "জ্যাকেট ও আউটারওয়্যার"),
    slug: "jackets-outerwear",
    parentId: "cat-men",
    level: 1,
    order: 5,
    isActive: true,
  },
  {
    _id: "cat-men-ethnic",
    name: i18n("Ethnic Wear", "এথনিক পোশাক"),
    slug: "ethnic-wear",
    parentId: "cat-men",
    level: 1,
    order: 6,
    isActive: true,
  },
  {
    _id: "cat-men-shorts",
    name: i18n("Shorts", "শর্টস"),
    slug: "shorts",
    parentId: "cat-men",
    level: 1,
    order: 7,
    isActive: true,
  },
  {
    _id: "cat-men-sweater",
    name: i18n("Sweaters", "সোয়েটার"),
    slug: "sweaters",
    parentId: "cat-men",
    level: 1,
    order: 8,
    isActive: true,
  },

  // ── Women categories (level 1) ──
  {
    _id: "cat-women-top",
    name: i18n("Tops", "টপস"),
    slug: "tops",
    parentId: "cat-women",
    level: 1,
    order: 1,
    isActive: true,
  },
  {
    _id: "cat-women-dress",
    name: i18n("Dresses", "ড্রেস"),
    slug: "dresses",
    parentId: "cat-women",
    level: 1,
    order: 2,
    isActive: true,
  },
  {
    _id: "cat-women-tshirt",
    name: i18n("T-Shirts", "টি-শার্ট"),
    slug: "t-shirts",
    parentId: "cat-women",
    level: 1,
    order: 3,
    isActive: true,
  },
  {
    _id: "cat-women-trouser",
    name: i18n("Trousers & Pants", "ট্রাউজার ও প্যান্ট"),
    slug: "trousers-pants",
    parentId: "cat-women",
    level: 1,
    order: 4,
    isActive: true,
  },
  {
    _id: "cat-women-skirt",
    name: i18n("Skirts", "স্কার্ট"),
    slug: "skirts",
    parentId: "cat-women",
    level: 1,
    order: 5,
    isActive: true,
  },
  {
    _id: "cat-women-kurti",
    name: i18n("Kurti & Kameez", "কুরতি ও কামিজ"),
    slug: "kurti-kameez",
    parentId: "cat-women",
    level: 1,
    order: 6,
    isActive: true,
  },
  {
    _id: "cat-women-sharee",
    name: i18n("Sharee", "শাড়ী"),
    slug: "sharee",
    parentId: "cat-women",
    level: 1,
    order: 7,
    isActive: true,
  },
  {
    _id: "cat-women-cardigan",
    name: i18n("Cardigans & Jackets", "কার্ডিগান ও জ্যাকেট"),
    slug: "cardigans-jackets",
    parentId: "cat-women",
    level: 1,
    order: 8,
    isActive: true,
  },
  {
    _id: "cat-women-hoodie",
    name: i18n("Hoodies & Sweatshirts", "হুডি ও সোয়েটশার্ট"),
    slug: "hoodies-sweatshirts",
    parentId: "cat-women",
    level: 1,
    order: 9,
    isActive: true,
  },
  {
    _id: "cat-women-blouse",
    name: i18n("Blouses & Shirts", "ব্লাউজ ও শার্ট"),
    slug: "blouses-shirts",
    parentId: "cat-women",
    level: 1,
    order: 10,
    isActive: true,
  },

  // ── Bags categories (level 1) ──
  {
    _id: "cat-bag-backpack",
    name: i18n("Backpacks", "ব্যাকপ্যাক"),
    slug: "backpacks",
    parentId: "cat-bags",
    level: 1,
    order: 1,
    isActive: true,
  },
  {
    _id: "cat-bag-handbag",
    name: i18n("Handbags", "হ্যান্ডব্যাগ"),
    slug: "handbags",
    parentId: "cat-bags",
    level: 1,
    order: 2,
    isActive: true,
  },
  {
    _id: "cat-bag-sling",
    name: i18n("Sling & Crossbody", "স্লিং ও ক্রসবডি"),
    slug: "sling-crossbody",
    parentId: "cat-bags",
    level: 1,
    order: 3,
    isActive: true,
  },
  {
    _id: "cat-bag-tote",
    name: i18n("Tote Bags", "টোট ব্যাগ"),
    slug: "tote-bags",
    parentId: "cat-bags",
    level: 1,
    order: 4,
    isActive: true,
  },
  {
    _id: "cat-bag-duffle",
    name: i18n("Duffle & Travel", "ডাফল ও ট্রাভেল"),
    slug: "duffle-travel",
    parentId: "cat-bags",
    level: 1,
    order: 5,
    isActive: true,
  },
  {
    _id: "cat-bag-wallet",
    name: i18n("Wallets & Pouches", "ওয়ালেট ও পাউচ"),
    slug: "wallets-pouches",
    parentId: "cat-bags",
    level: 1,
    order: 6,
    isActive: true,
  },

  // ── Household categories (level 1) ──
  {
    _id: "cat-house-bedding",
    name: i18n("Bedding & Linens", "বেডিং ও লিনেন"),
    slug: "bedding-linens",
    parentId: "cat-household",
    level: 1,
    order: 1,
    isActive: true,
  },
  {
    _id: "cat-house-kitchen",
    name: i18n("Kitchen & Dining", "রান্নাঘর ও ডাইনিং"),
    slug: "kitchen-dining",
    parentId: "cat-household",
    level: 1,
    order: 2,
    isActive: true,
  },
  {
    _id: "cat-house-decor",
    name: i18n("Home Decor", "হোম ডেকোর"),
    slug: "home-decor",
    parentId: "cat-household",
    level: 1,
    order: 3,
    isActive: true,
  },
  {
    _id: "cat-house-storage",
    name: i18n("Storage & Organization", "স্টোরেজ ও সংগঠন"),
    slug: "storage-organization",
    parentId: "cat-household",
    level: 1,
    order: 4,
    isActive: true,
  },
];

// ─── 4. Products ───────────────────────────────────────────────────────────
// Image URLs are placeholders — replace with real R2 URLs.

export const products = [
  // ── Men > T-Shirts ──
  {
    _id: "prod-001",
    sku: "TBD-MTS-001",
    slug: "nike-crewneck-tshirt-black",
    title: i18n("Nike Crewneck T-Shirt", "নাইকি ক্রুনেক টি-শার্ট"),
    brand: "Nike",
    categoryId: "cat-men-tshirt",
    categoryPath: i18n("Men / T-Shirts", "পুরুষ / টি-শার্ট"),
    price: 850,
    compareAtPrice: 1800,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Nike+Tee+Black",
        key: "dummy/prod-001-1.jpg",
        alt: i18n("Nike crewneck t-shirt in black, front view"),
        order: 0,
      },
    ],
    size: { type: "standard", standard: "M" },
    colorId: "color-black",
    color: i18n("Black", "কালো"),
    ownerId: "owner-me",
    owner: "Saif",
    grade: "T",
    condition: "Excellent" as const,
    notes: i18n("Lightly worn, no stains or fading. 100% cotton."),
    stock: 1,
    status: "ACTIVE" as const,
  },
  {
    _id: "prod-002",
    sku: "TBD-MTS-002",
    slug: "adicolor-essentials-tshirt-white",
    title: i18n("Adicolor Essentials T-Shirt", "অ্যাডিকালার এসেনশিয়ালস টি-শার্ট"),
    brand: "Adidas",
    categoryId: "cat-men-tshirt",
    categoryPath: i18n("Men / T-Shirts", "পুরুষ / টি-শার্ট"),
    price: 780,
    compareAtPrice: 1500,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Adicolor+Tee+White",
        key: "dummy/prod-002-1.jpg",
        alt: i18n("Adicolor essentials t-shirt in white, front view"),
        order: 0,
      },
    ],
    size: { type: "standard", standard: "L" },
    colorId: "color-white",
    color: i18n("White", "সাদা"),
    ownerId: "owner-me",
    owner: "Saif",
    grade: "T",
    condition: "Good" as const,
    notes: i18n("Gently used, slight fade on collar."),
    stock: 1,
    status: "ACTIVE" as const,
  },
  {
    _id: "prod-003",
    sku: "TBD-MTS-003",
    slug: "uniqlo-packaged-oversized-tshirt-navy",
    title: i18n("Uniqlo Packaged Oversized T-Shirt", "ইউনিক্লো প্যাকেজড ওভারসাইজড টি-শার্ট"),
    brand: "Uniqlo",
    categoryId: "cat-men-tshirt",
    categoryPath: i18n("Men / T-Shirts", "পুরুষ / টি-শার্ট"),
    price: 650,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Uniqlo+Tee+Navy",
        key: "dummy/prod-003-1.jpg",
        alt: i18n("Uniqlo oversized t-shirt in navy, front view"),
        order: 0,
      },
    ],
    size: { type: "standard", standard: "S" },
    colorId: "color-navy",
    color: i18n("Navy", "নেভি ব্লু"),
    ownerId: "owner-shaikh",
    owner: "Shaikh",
    grade: "B",
    condition: "Excellent" as const,
    stock: 1,
    status: "ACTIVE" as const,
  },
  {
    _id: "prod-004",
    sku: "TBD-MTS-004",
    slug: "carhartt-graphic-tshirt-gray",
    title: i18n("Carhartt Graphic T-Shirt", "কারহার্ট গ্রাফিক টি-শার্ট"),
    brand: "Carhartt",
    categoryId: "cat-men-tshirt",
    categoryPath: i18n("Men / T-Shirts", "পুরুষ / টি-শার্ট"),
    price: 950,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Carhartt+Graphic+Gray",
        key: "dummy/prod-004-1.jpg",
        alt: i18n("Carhartt graphic t-shirt in gray, front view"),
        order: 0,
      },
    ],
    size: { type: "standard", standard: "XL" },
    colorId: "color-gray",
    color: i18n("Gray", "ধূসর"),
    ownerId: "owner-me",
    owner: "Saif",
    grade: "T",
    condition: "Excellent" as const,
    stock: 1,
    status: "ACTIVE" as const,
  },

  // ── Men > Shirts ──
  {
    _id: "prod-005",
    sku: "TBD-MSH-001",
    slug: "tommy-hilfiger-casual-shirt-blue",
    title: i18n("Tommy Hilfiger Casual Shirt", "টমি হিলফিগার ক্যাজুয়াল শার্ট"),
    brand: "Tommy Hilfiger",
    categoryId: "cat-men-shirt",
    categoryPath: i18n("Men / Shirts", "পুরুষ / শার্ট"),
    price: 1200,
    compareAtPrice: 3000,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Tommy+Shirt+Blue",
        key: "dummy/prod-005-1.jpg",
        alt: i18n("Tommy Hilfiger casual shirt in blue, front"),
        order: 0,
      },
    ],
    size: { type: "standard", standard: "L" },
    colorId: "color-blue",
    color: i18n("Blue", "নীল"),
    ownerId: "owner-shaikh",
    owner: "Shaikh",
    grade: "T",
    condition: "Excellent" as const,
    stock: 1,
    status: "ACTIVE" as const,
  },
  {
    _id: "prod-006",
    sku: "TBD-MSH-002",
    slug: "zara-linen-shirt-beige",
    title: i18n("Zara Linen Shirt", "জারা লিনেন শার্ট"),
    brand: "Zara",
    categoryId: "cat-men-shirt",
    categoryPath: i18n("Men / Shirts", "পুরুষ / শার্ট"),
    price: 1100,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Zara+Linen+Beige",
        key: "dummy/prod-006-1.jpg",
        alt: i18n("Zara linen shirt in beige, front view"),
        order: 0,
      },
    ],
    size: { type: "standard", standard: "M" },
    colorId: "color-beige",
    color: i18n("Beige", "বেইজ"),
    ownerId: "owner-me",
    owner: "Saif",
    grade: "T",
    condition: "Good" as const,
    notes: i18n("Light wear, one small button missing (included in pouch)."),
    stock: 1,
    status: "ACTIVE" as const,
  },
  {
    _id: "prod-007",
    sku: "TBD-MSH-003",
    slug: "levis-checked-shirt-red",
    title: i18n("Levi's Checked Shirt", "লেভাইস চেক শার্ট"),
    brand: "Levi's",
    categoryId: "cat-men-shirt",
    categoryPath: i18n("Men / Shirts", "পুরুষ / শার্ট"),
    price: 990,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Levis+Check+Red",
        key: "dummy/prod-007-1.jpg",
        alt: i18n("Levi's checked shirt in red, front view"),
        order: 0,
      },
    ],
    size: { type: "standard", standard: "L" },
    colorId: "color-red",
    color: i18n("Red", "লাল"),
    ownerId: "owner-rahim",
    owner: "Rahim",
    grade: "B",
    condition: "Excellent" as const,
    stock: 1,
    status: "ACTIVE" as const,
  },

  // ── Men > Trousers ──
  {
    _id: "prod-008",
    sku: "TBD-MTR-001",
    slug: "uniqlo-smart-cargo-pants-black",
    title: i18n("Uniqlo Smart Cargo Pants", "ইউনিক্লো স্মার্ট কার্গো প্যান্ট"),
    brand: "Uniqlo",
    categoryId: "cat-men-trouser",
    categoryPath: i18n("Men / Trousers", "পুরুষ / ট্রাউজার"),
    price: 1350,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Uniqlo+Cargo+Black",
        key: "dummy/prod-008-1.jpg",
        alt: i18n("Uniqlo smart cargo pants in black, front"),
        order: 0,
      },
    ],
    size: { type: "standard", standard: "32" },
    colorId: "color-black",
    color: i18n("Black", "কালো"),
    ownerId: "owner-me",
    owner: "Saif",
    grade: "T",
    condition: "Excellent" as const,
    stock: 1,
    status: "ACTIVE" as const,
  },
  {
    _id: "prod-009",
    sku: "TBD-MTR-002",
    slug: "zara-slim-fit-chinos-khaki",
    title: i18n("Zara Slim Fit Chinos", "জারা স্লিম ফিট চিনোস"),
    brand: "Zara",
    categoryId: "cat-men-trouser",
    categoryPath: i18n("Men / Trousers", "পুরুষ / ট্রাউজার"),
    price: 1250,
    compareAtPrice: 2500,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Zara+Chinos+Khaki",
        key: "dummy/prod-009-1.jpg",
        alt: i18n("Zara slim fit chinos in khaki, front"),
        order: 0,
      },
    ],
    size: { type: "standard", standard: "30" },
    colorId: "color-khaki",
    color: i18n("Khaki", "খাকি"),
    ownerId: "owner-rahim",
    owner: "Rahim",
    grade: "W",
    condition: "Good" as const,
    notes: i18n("Worn a few times, still crisp."),
    stock: 1,
    status: "ACTIVE" as const,
  },

  // ── Men > Hoodies & Sweatshirts ──
  {
    _id: "prod-010",
    sku: "TBD-MHO-001",
    slug: "champion-reverse-weave-hoodie-navy",
    title: i18n("Champion Reverse Weave Hoodie", "চ্যাম্পিয়ন রিভার্স উইভ হুডি"),
    brand: "Champion",
    categoryId: "cat-men-hoodie",
    categoryPath: i18n("Men / Hoodies & Sweatshirts", "পুরুষ / হুডি ও সোয়েটশার্ট"),
    price: 1850,
    compareAtPrice: 3500,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Champion+Hoodie+Navy",
        key: "dummy/prod-010-1.jpg",
        alt: i18n("Champion Reverse Weave hoodie in navy, front"),
        order: 0,
      },
    ],
    size: { type: "standard", standard: "M" },
    colorId: "color-navy",
    color: i18n("Navy", "নেভি ব্লু"),
    ownerId: "owner-me",
    owner: "Saif",
    grade: "T",
    condition: "Excellent" as const,
    stock: 1,
    status: "ACTIVE" as const,
  },
  {
    _id: "prod-011",
    sku: "TBD-MHO-002",
    slug: "nike-club-fleece-sweatshirt-gray",
    title: i18n("Nike Club Fleece Sweatshirt", "নাইকি ক্লাব ফ্লিস সোয়েটশার্ট"),
    brand: "Nike",
    categoryId: "cat-men-hoodie",
    categoryPath: i18n("Men / Hoodies & Sweatshirts", "পুরুষ / হুডি ও সোয়েটশার্ট"),
    price: 1450,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Nike+Sweatshirt+Gray",
        key: "dummy/prod-011-1.jpg",
        alt: i18n("Nike Club Fleece sweatshirt in gray, front"),
        order: 0,
      },
    ],
    size: { type: "standard", standard: "L" },
    colorId: "color-gray",
    color: i18n("Gray", "ধূসর"),
    ownerId: "owner-me",
    owner: "Saif",
    grade: "T",
    condition: "Good" as const,
    notes: i18n("Pilled slightly on sleeves, otherwise great."),
    stock: 1,
    status: "ACTIVE" as const,
  },

  // ── Men > Jackets & Outerwear ──
  {
    _id: "prod-012",
    sku: "TBD-MJA-001",
    slug: "north-face-nuptse-jacket-black",
    title: i18n("The North Face Nuptse Jacket", "দ্য নর্থ ফেস নাপসি জ্যাকেট"),
    brand: "The North Face",
    categoryId: "cat-men-jacket",
    categoryPath: i18n("Men / Jackets & Outerwear", "পুরুষ / জ্যাকেট ও আউটারওয়্যার"),
    price: 2800,
    compareAtPrice: 5500,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=TNF+Nuptse+Black",
        key: "dummy/prod-012-1.jpg",
        alt: i18n("North Face Nuptse jacket in black, front"),
        order: 0,
      },
    ],
    size: { type: "standard", standard: "M" },
    colorId: "color-black",
    color: i18n("Black", "কালো"),
    ownerId: "owner-shaikh",
    owner: "Shaikh",
    grade: "T",
    condition: "Excellent" as const,
    stock: 1,
    status: "ACTIVE" as const,
  },
  {
    _id: "prod-013",
    sku: "TBD-MJA-002",
    slug: "zara-bomber-jacket-olive",
    title: i18n("Zara Bomber Jacket", "জারা বম্বার জ্যাকেট"),
    brand: "Zara",
    categoryId: "cat-men-jacket",
    categoryPath: i18n("Men / Jackets & Outerwear", "পুরুষ / জ্যাকেট ও আউটারওয়্যার"),
    price: 1650,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Zara+Bomber+Olive",
        key: "dummy/prod-013-1.jpg",
        alt: i18n("Zara bomber jacket in olive, front view"),
        order: 0,
      },
    ],
    size: { type: "standard", standard: "L" },
    colorId: "color-olive",
    color: i18n("Olive", "অলিভ"),
    ownerId: "owner-rahim",
    owner: "Rahim",
    grade: "W",
    condition: "Fair" as const,
    notes: i18n("Zipper replaced. Some fraying at cuffs."),
    stock: 1,
    status: "ACTIVE" as const,
  },

  // ── Men > Ethnic Wear ──
  {
    _id: "prod-014",
    sku: "TBD-MET-001",
    slug: "punjabi-kurta-white-cotton",
    title: i18n("Punjabi Kurta — White Cotton", "পাঞ্জাবি — সাদা কটন"),
    brand: "Gentle Park",
    categoryId: "cat-men-ethnic",
    categoryPath: i18n("Men / Ethnic Wear", "পুরুষ / এথনিক পোশাক"),
    price: 980,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Kurta+White",
        key: "dummy/prod-014-1.jpg",
        alt: i18n("White cotton Punjabi kurta, front view"),
        order: 0,
      },
    ],
    size: { type: "standard", standard: "40" },
    colorId: "color-white",
    color: i18n("White", "সাদা"),
    ownerId: "owner-me",
    owner: "Saif",
    grade: "B",
    condition: "Excellent" as const,
    stock: 1,
    status: "ACTIVE" as const,
  },

  // ── Men > Shorts ──
  {
    _id: "prod-015",
    sku: "TBD-MSHO-001",
    slug: "nike-dri-fit-training-shorts-black",
    title: i18n("Nike Dri-FIT Training Shorts", "নাইকি ড্রাই-ফিট ট্রেনিং শর্টস"),
    brand: "Nike",
    categoryId: "cat-men-shorts",
    categoryPath: i18n("Men / Shorts", "পুরুষ / শর্টস"),
    price: 750,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Nike+Shorts+Black",
        key: "dummy/prod-015-1.jpg",
        alt: i18n("Nike Dri-FIT training shorts in black, front"),
        order: 0,
      },
    ],
    size: { type: "standard", standard: "M" },
    colorId: "color-black",
    color: i18n("Black", "কালো"),
    ownerId: "owner-me",
    owner: "Saif",
    grade: "T",
    condition: "Good" as const,
    stock: 1,
    status: "ACTIVE" as const,
  },

  // ── Men > Sweaters ──
  {
    _id: "prod-016",
    sku: "TBD-MSW-001",
    slug: "h-m-cable-knit-sweater-cream",
    title: i18n("H&M Cable Knit Sweater", "এইচএন্ডএম কেবল নিট সোয়েটার"),
    brand: "H&M",
    categoryId: "cat-men-sweater",
    categoryPath: i18n("Men / Sweaters", "পুরুষ / সোয়েটার"),
    price: 1100,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=HM+Sweater+Cream",
        key: "dummy/prod-016-1.jpg",
        alt: i18n("H&M cable knit sweater in cream, front view"),
        order: 0,
      },
    ],
    size: { type: "standard", standard: "L" },
    colorId: "color-cream",
    color: i18n("Cream", "ক্রিম"),
    ownerId: "owner-shaikh",
    owner: "Shaikh",
    grade: "T",
    condition: "Excellent" as const,
    stock: 1,
    status: "ACTIVE" as const,
  },

  // ── Women > Tops ──
  {
    _id: "prod-017",
    sku: "TBD-WTP-001",
    slug: "zara-corset-top-black",
    title: i18n("Zara Corset Top", "জারা কর্সেট টপ"),
    brand: "Zara",
    categoryId: "cat-women-top",
    categoryPath: i18n("Women / Tops", "মহিলা / টপস"),
    price: 890,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Zara+Corset+Black",
        key: "dummy/prod-017-1.jpg",
        alt: i18n("Zara corset top in black, front view"),
        order: 0,
      },
    ],
    size: { type: "standard", standard: "S" },
    colorId: "color-black",
    color: i18n("Black", "কালো"),
    ownerId: "owner-me",
    owner: "Saif",
    grade: "T",
    condition: "Excellent" as const,
    stock: 1,
    status: "ACTIVE" as const,
  },
  {
    _id: "prod-018",
    sku: "TBD-WTP-002",
    slug: "h-m-cropped-knit-top-cream",
    title: i18n("H&M Cropped Knit Top", "এইচএন্ডএম ক্রপড নিট টপ"),
    brand: "H&M",
    categoryId: "cat-women-top",
    categoryPath: i18n("Women / Tops", "মহিলা / টপস"),
    price: 650,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=HM+Knit+Top+Cream",
        key: "dummy/prod-018-1.jpg",
        alt: i18n("H&M cropped knit top in cream, front view"),
        order: 0,
      },
    ],
    size: { type: "standard", standard: "M" },
    colorId: "color-cream",
    color: i18n("Cream", "ক্রিম"),
    ownerId: "owner-rahim",
    owner: "Rahim",
    grade: "B",
    condition: "Good" as const,
    stock: 1,
    status: "ACTIVE" as const,
  },
  {
    _id: "prod-019",
    sku: "TBD-WTP-003",
    slug: "mango-ruffle-sleeve-top-white",
    title: i18n("Mango Ruffle Sleeve Top", "ম্যাঙ্গো রাফেল স্লিভ টপ"),
    brand: "Mango",
    categoryId: "cat-women-top",
    categoryPath: i18n("Women / Tops", "মহিলা / টপস"),
    price: 720,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Mango+Top+White",
        key: "dummy/prod-019-1.jpg",
        alt: i18n("Mango ruffle sleeve top in white, front"),
        order: 0,
      },
    ],
    size: { type: "standard", standard: "S" },
    colorId: "color-white",
    color: i18n("White", "সাদা"),
    ownerId: "owner-me",
    owner: "Saif",
    grade: "T",
    condition: "Excellent" as const,
    stock: 1,
    status: "ACTIVE" as const,
  },

  // ── Women > Dresses ──
  {
    _id: "prod-020",
    sku: "TBD-WDR-001",
    slug: "zara-midi-dress- floral-blue",
    title: i18n("Zara Floral Midi Dress", "জারা ফ্লোরাল মিডি ড্রেস"),
    brand: "Zara",
    categoryId: "cat-women-dress",
    categoryPath: i18n("Women / Dresses", "মহিলা / ড্রেস"),
    price: 1450,
    compareAtPrice: 2800,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Zara+Floral+Dress",
        key: "dummy/prod-020-1.jpg",
        alt: i18n("Zara floral midi dress, front view"),
        order: 0,
      },
    ],
    size: { type: "standard", standard: "M" },
    colorId: "color-blue",
    color: i18n("Blue", "নীল"),
    ownerId: "owner-me",
    owner: "Saif",
    grade: "T",
    condition: "Excellent" as const,
    notes: i18n("Stunning floral print, perfect for summer outings."),
    stock: 1,
    status: "ACTIVE" as const,
  },
  {
    _id: "prod-021",
    sku: "TBD-WDR-002",
    slug: "h-m-bodycon-dress-black",
    title: i18n("H&M Bodycon Dress", "এইচএন্ডএম বডিকন ড্রেস"),
    brand: "H&M",
    categoryId: "cat-women-dress",
    categoryPath: i18n("Women / Dresses", "মহিলা / ড্রেস"),
    price: 990,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=HM+Bodycon+Black",
        key: "dummy/prod-021-1.jpg",
        alt: i18n("H&M bodycon dress in black, front view"),
        order: 0,
      },
    ],
    size: { type: "standard", standard: "XS" },
    colorId: "color-black",
    color: i18n("Black", "কালো"),
    ownerId: "owner-shaikh",
    owner: "Shaikh",
    grade: "O",
    condition: "Good" as const,
    notes: i18n("A wardrobe staple. Some slight stretching."),
    stock: 1,
    status: "ACTIVE" as const,
  },
  {
    _id: "prod-022",
    sku: "TBD-WDR-003",
    slug: "forever-21-mini-slip-dress-pink",
    title: i18n("Forever 21 Mini Slip Dress", "ফরএভার ২১ মিনি স্লিপ ড্রেস"),
    brand: "Forever 21",
    categoryId: "cat-women-dress",
    categoryPath: i18n("Women / Dresses", "মহিলা / ড্রেস"),
    price: 820,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=F21+Slip+Pink",
        key: "dummy/prod-022-1.jpg",
        alt: i18n("Forever 21 mini slip dress in pink, front"),
        order: 0,
      },
    ],
    size: { type: "standard", standard: "S" },
    colorId: "color-pink",
    color: i18n("Pink", "গোলাপী"),
    ownerId: "owner-me",
    owner: "Saif",
    grade: "M",
    condition: "Fair" as const,
    notes: i18n("Satin finish. Small pulled thread near hem."),
    stock: 1,
    status: "ACTIVE" as const,
  },

  // ── Women > T-Shirts ──
  {
    _id: "prod-023",
    sku: "TBD-WTS-001",
    slug: "nike-cropped-tshirt-white",
    title: i18n("Nike Cropped T-Shirt", "নাইকি ক্রপড টি-শার্ট"),
    brand: "Nike",
    categoryId: "cat-women-tshirt",
    categoryPath: i18n("Women / T-Shirts", "মহিলা / টি-শার্ট"),
    price: 750,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Nike+Cropped+White",
        key: "dummy/prod-023-1.jpg",
        alt: i18n("Nike cropped t-shirt in white, front view"),
        order: 0,
      },
    ],
    size: { type: "standard", standard: "M" },
    colorId: "color-white",
    color: i18n("White", "সাদা"),
    ownerId: "owner-rahim",
    owner: "Rahim",
    grade: "T",
    condition: "Excellent" as const,
    stock: 1,
    status: "ACTIVE" as const,
  },
  {
    _id: "prod-024",
    sku: "TBD-WTS-002",
    slug: "uniqlo-airism-cotton-oversized-tee-mustard",
    title: i18n("Uniqlo Airism Cotton Oversized Tee", "ইউনিক্লো এয়ারিজম কটন ওভারসাইজড টি"),
    brand: "Uniqlo",
    categoryId: "cat-women-tshirt",
    categoryPath: i18n("Women / T-Shirts", "মহিলা / টি-শার্ট"),
    price: 680,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Uniqlo+Tee+Mustard",
        key: "dummy/prod-024-1.jpg",
        alt: i18n("Uniqlo oversized tee in mustard, front view"),
        order: 0,
      },
    ],
    size: { type: "standard", standard: "L" },
    colorId: "color-mustard",
    color: i18n("Mustard", "সরিষে হলুদ"),
    ownerId: "owner-me",
    owner: "Saif",
    grade: "T",
    condition: "Excellent" as const,
    stock: 1,
    status: "ACTIVE" as const,
  },

  // ── Women > Trousers & Pants ──
  {
    _id: "prod-025",
    sku: "TBD-WTR-001",
    slug: "h-m-wide-leg-linen-pants-beige",
    title: i18n("H&M Wide Leg Linen Pants", "এইচএন্ডএম ওয়াইড লেগ লিনেন প্যান্ট"),
    brand: "H&M",
    categoryId: "cat-women-trouser",
    categoryPath: i18n("Women / Trousers & Pants", "মহিলা / ট্রাউজার ও প্যান্ট"),
    price: 1150,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=HM+Linen+Pants",
        key: "dummy/prod-025-1.jpg",
        alt: i18n("H&M wide leg linen pants in beige, front"),
        order: 0,
      },
    ],
    size: { type: "standard", standard: "M" },
    colorId: "color-beige",
    color: i18n("Beige", "বেইজ"),
    ownerId: "owner-shaikh",
    owner: "Shaikh",
    grade: "T",
    condition: "Excellent" as const,
    stock: 1,
    status: "ACTIVE" as const,
  },

  // ── Women > Skirts ──
  {
    _id: "prod-026",
    sku: "TBD-WSK-001",
    slug: "mango-pleated-mini-skirt-black",
    title: i18n("Mango Pleated Mini Skirt", "ম্যাঙ্গো প্লিটেড মিনি স্কার্ট"),
    brand: "Mango",
    categoryId: "cat-women-skirt",
    categoryPath: i18n("Women / Skirts", "মহিলা / স্কার্ট"),
    price: 850,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Mango+Skirt+Black",
        key: "dummy/prod-026-1.jpg",
        alt: i18n("Mango pleated mini skirt in black, front"),
        order: 0,
      },
    ],
    size: { type: "standard", standard: "S" },
    colorId: "color-black",
    color: i18n("Black", "কালো"),
    ownerId: "owner-me",
    owner: "Saif",
    grade: "T",
    condition: "Excellent" as const,
    stock: 1,
    status: "ACTIVE" as const,
  },

  // ── Women > Kurti & Kameez ──
  {
    _id: "prod-027",
    sku: "TBD-WKU-001",
    slug: "kurti-cotton-block-print-green",
    title: i18n("Cotton Block Print Kurti", "কটন ব্লক প্রিন্ট কুরতি"),
    brand: "Rang",
    categoryId: "cat-women-kurti",
    categoryPath: i18n("Women / Kurti & Kameez", "মহিলা / কুরতি ও কামিজ"),
    price: 920,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Kurti+Green",
        key: "dummy/prod-027-1.jpg",
        alt: i18n("Cotton block print kurti in green, front"),
        order: 0,
      },
    ],
    size: { type: "standard", standard: "M" },
    colorId: "color-green",
    color: i18n("Green", "সবুজ"),
    ownerId: "owner-me",
    owner: "Saif",
    grade: "T",
    condition: "Excellent" as const,
    stock: 1,
    status: "ACTIVE" as const,
  },

  // ── Women > Sharee ──
  {
    _id: "prod-028",
    sku: "TBD-WSH-001",
    slug: "taant-sharee-cotton-red-border",
    title: i18n("Taant Cotton Sharee — Red Border", "তাঁত কটন শাড়ী — লাল পাড়"),
    brand: "Tangail Taant",
    categoryId: "cat-women-sharee",
    categoryPath: i18n("Women / Sharee", "মহিলা / শাড়ী"),
    price: 1650,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Sharee+Red+Border",
        key: "dummy/prod-028-1.jpg",
        alt: i18n("Taant cotton sharee with red border"),
        order: 0,
      },
    ],
    size: { type: "custom", custom: "5.5 meters × 45 inches" },
    colorId: "color-cream",
    color: i18n("Cream", "ক্রিম"),
    ownerId: "owner-me",
    owner: "Saif",
    grade: "O",
    condition: "Good" as const,
    notes: i18n("Hand-woven, slight color variation is natural."),
    stock: 1,
    status: "ACTIVE" as const,
  },

  // ── Women > Cardigans & Jackets ──
  {
    _id: "prod-029",
    sku: "TBD-WCA-001",
    slug: "zara-knit-cardigan-beige",
    title: i18n("Zara Knit Cardigan", "জারা নিট কার্ডিগান"),
    brand: "Zara",
    categoryId: "cat-women-cardigan",
    categoryPath: i18n("Women / Cardigans & Jackets", "মহিলা / কার্ডিগান ও জ্যাকেট"),
    price: 1250,
    compareAtPrice: 2200,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Zara+Cardigan+Beige",
        key: "dummy/prod-029-1.jpg",
        alt: i18n("Zara knit cardigan in beige, front view"),
        order: 0,
      },
    ],
    size: { type: "standard", standard: "M" },
    colorId: "color-beige",
    color: i18n("Beige", "বেইজ"),
    ownerId: "owner-rahim",
    owner: "Rahim",
    grade: "M",
    condition: "Good" as const,
    stock: 1,
    status: "ACTIVE" as const,
  },

  // ── Women > Blouses & Shirts ──
  {
    _id: "prod-030",
    sku: "TBD-WBL-001",
    slug: "mango-satin-shirt-coral",
    title: i18n("Mango Satin Shirt", "ম্যাঙ্গো সাটিন শার্ট"),
    brand: "Mango",
    categoryId: "cat-women-blouse",
    categoryPath: i18n("Women / Blouses & Shirts", "মহিলা / ব্লাউজ ও শার্ট"),
    price: 1050,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Mango+Satin+Coral",
        key: "dummy/prod-030-1.jpg",
        alt: i18n("Mango satin shirt in coral, front view"),
        order: 0,
      },
    ],
    size: { type: "standard", standard: "S" },
    colorId: "color-coral",
    color: i18n("Coral", "কোরাল"),
    ownerId: "owner-me",
    owner: "Saif",
    grade: "T",
    condition: "Excellent" as const,
    stock: 1,
    status: "ACTIVE" as const,
  },

  // ── Bags > Backpacks ──
  {
    _id: "prod-031",
    sku: "TBD-BBP-001",
    slug: "nike-academy-backpack-black",
    title: i18n("Nike Academy Backpack", "নাইকি একাডেমি ব্যাকপ্যাক"),
    brand: "Nike",
    categoryId: "cat-bag-backpack",
    categoryPath: i18n("Bags / Backpacks", "ব্যাগ / ব্যাকপ্যাক"),
    price: 1450,
    compareAtPrice: 2500,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Nike+Backpack+Black",
        key: "dummy/prod-031-1.jpg",
        alt: i18n("Nike Academy backpack in black, front view"),
        order: 0,
      },
    ],
    size: { type: "custom", custom: "46 × 30 × 18 cm" },
    colorId: "color-black",
    color: i18n("Black", "কালো"),
    ownerId: "owner-me",
    owner: "Saif",
    grade: "T",
    condition: "Excellent" as const,
    stock: 1,
    status: "ACTIVE" as const,
  },
  {
    _id: "prod-032",
    sku: "TBD-BBP-002",
    slug: "jansport-superbreak-backpack-navy",
    title: i18n("JanSport SuperBreak Backpack", "জ্যান্সস্পোর্ট সুপারব্রেক ব্যাকপ্যাক"),
    brand: "JanSport",
    categoryId: "cat-bag-backpack",
    categoryPath: i18n("Bags / Backpacks", "ব্যাগ / ব্যাকপ্যাক"),
    price: 1200,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=JanSport+Backpack",
        key: "dummy/prod-032-1.jpg",
        alt: i18n("JanSport SuperBreak backpack in navy, front"),
        order: 0,
      },
    ],
    size: { type: "custom", custom: "43 × 33 × 21 cm" },
    colorId: "color-navy",
    color: i18n("Navy", "নেভি ব্লু"),
    ownerId: "owner-shaikh",
    owner: "Shaikh",
    grade: "B",
    condition: "Good" as const,
    notes: i18n("Small scuff on bottom corner."),
    stock: 1,
    status: "ACTIVE" as const,
  },

  // ── Bags > Handbags ──
  {
    _id: "prod-033",
    sku: "TBD-BHB-001",
    slug: "zara-tote-handbag-brown",
    title: i18n("Zara Tote Handbag", "জারা টোট হ্যান্ডব্যাগ"),
    brand: "Zara",
    categoryId: "cat-bag-handbag",
    categoryPath: i18n("Bags / Handbags", "ব্যাগ / হ্যান্ডব্যাগ"),
    price: 1600,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Zara+Handbag+Brown",
        key: "dummy/prod-033-1.jpg",
        alt: i18n("Zara tote handbag in brown, front view"),
        order: 0,
      },
    ],
    size: { type: "custom", custom: "32 × 26 × 12 cm" },
    colorId: "color-brown",
    color: i18n("Brown", "বাদামী"),
    ownerId: "owner-me",
    owner: "Saif",
    grade: "T",
    condition: "Excellent" as const,
    stock: 1,
    status: "ACTIVE" as const,
  },

  // ── Bags > Sling & Crossbody ──
  {
    _id: "prod-034",
    sku: "TBD-BSL-001",
    slug: "uniqlo-round-mini-shoulder-bag-black",
    title: i18n("Uniqlo Round Mini Shoulder Bag", "ইউনিক্লো রাউন্ড মিনি শোল্ডার ব্যাগ"),
    brand: "Uniqlo",
    categoryId: "cat-bag-sling",
    categoryPath: i18n("Bags / Sling & Crossbody", "ব্যাগ / স্লিং ও ক্রসবডি"),
    price: 950,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Uniqlo+Sling+Black",
        key: "dummy/prod-034-1.jpg",
        alt: i18n("Uniqlo round mini shoulder bag in black"),
        order: 0,
      },
    ],
    size: { type: "custom", custom: "17 × 12 × 7 cm" },
    colorId: "color-black",
    color: i18n("Black", "কালো"),
    ownerId: "owner-me",
    owner: "Saif",
    grade: "T",
    condition: "Excellent" as const,
    stock: 1,
    status: "ACTIVE" as const,
  },

  // ── Bags > Tote Bags ──
  {
    _id: "prod-035",
    sku: "TBD-BTO-001",
    slug: "canvas-market-tote-cream-printed",
    title: i18n("Canvas Market Tote — Cream", "ক্যানভাস মার্কেট টোট — ক্রিম"),
    brand: "Generic",
    categoryId: "cat-bag-tote",
    categoryPath: i18n("Bags / Tote Bags", "ব্যাগ / টোট ব্যাগ"),
    price: 550,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Canvas+Tote+Cream",
        key: "dummy/prod-035-1.jpg",
        alt: i18n("Canvas market tote in cream, front view"),
        order: 0,
      },
    ],
    size: { type: "custom", custom: "40 × 35 cm" },
    colorId: "color-cream",
    color: i18n("Cream", "ক্রিম"),
    ownerId: "owner-shaikh",
    owner: "Shaikh",
    grade: "M",
    condition: "Good" as const,
    notes: i18n("Sturdy canvas. Minor ink mark on one side."),
    stock: 1,
    status: "ACTIVE" as const,
  },

  // ── Bags > Duffle & Travel ──
  {
    _id: "prod-036",
    sku: "TBD-BDU-001",
    slug: "adidas-diablo-small-duffle-black",
    title: i18n("Adidas Diablo Small Duffle", "অ্যাডিডাস ডিয়াবলো স্মল ডাফল"),
    brand: "Adidas",
    categoryId: "cat-bag-duffle",
    categoryPath: i18n("Bags / Duffle & Travel", "ব্যাগ / ডাফল ও ট্রাভেল"),
    price: 1750,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Adidas+Duffle+Black",
        key: "dummy/prod-036-1.jpg",
        alt: i18n("Adidas Diablo small duffle bag in black"),
        order: 0,
      },
    ],
    size: { type: "custom", custom: "48 × 28 × 25 cm" },
    colorId: "color-black",
    color: i18n("Black", "কালো"),
    ownerId: "owner-me",
    owner: "Saif",
    grade: "T",
    condition: "Excellent" as const,
    stock: 1,
    status: "ACTIVE" as const,
  },

  // ── Bags > Wallets & Pouches ──
  {
    _id: "prod-037",
    sku: "TBD-BWA-001",
    slug: "nike-heritage-wallet-black",
    title: i18n("Nike Heritage Wallet", "নাইকি হেরিটেজ ওয়ালেট"),
    brand: "Nike",
    categoryId: "cat-bag-wallet",
    categoryPath: i18n("Bags / Wallets & Pouches", "ব্যাগ / ওয়ালেট ও পাউচ"),
    price: 550,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Nike+Wallet+Black",
        key: "dummy/prod-037-1.jpg",
        alt: i18n("Nike Heritage wallet in black"),
        order: 0,
      },
    ],
    size: { type: "custom", custom: "11 × 9 cm" },
    colorId: "color-black",
    color: i18n("Black", "কালো"),
    ownerId: "owner-me",
    owner: "Saif",
    grade: "T",
    condition: "Excellent" as const,
    stock: 1,
    status: "ACTIVE" as const,
  },

  // ── Household > Bedding & Linens ──
  {
    _id: "prod-038",
    sku: "TBD-HBE-001",
    slug: "cotton-fitted-sheet-set-beige-double",
    title: i18n("Cotton Fitted Sheet Set — Double", "কটন ফিটেড শীট সেট — ডাবল"),
    brand: "Home Pro",
    categoryId: "cat-house-bedding",
    categoryPath: i18n("Household / Bedding & Linens", "গৃহস্থালী / বেডিং ও লিনেন"),
    price: 980,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Sheet+Set+Beige",
        key: "dummy/prod-038-1.jpg",
        alt: i18n("Cotton fitted sheet set in beige, double size"),
        order: 0,
      },
    ],
    size: { type: "custom", custom: "Double (180×200 cm + 2 pillowcases)" },
    colorId: "color-beige",
    color: i18n("Beige", "বেইজ"),
    ownerId: "owner-shaikh",
    owner: "Shaikh",
    grade: "O",
    condition: "Excellent" as const,
    notes: i18n("New with tags. 300 TC, 100% cotton."),
    stock: 1,
    status: "ACTIVE" as const,
  },

  // ── Household > Kitchen & Dining ──
  {
    _id: "prod-039",
    sku: "TBD-HKI-001",
    slug: "ceramic-mixing-bowl-set-cream-3pcs",
    title: i18n("Ceramic Mixing Bowl Set 3pc", "সিরামিক মিক্সিং বাওল সেট ৩ পিস"),
    brand: "IKEA",
    categoryId: "cat-house-kitchen",
    categoryPath: i18n("Household / Kitchen & Dining", "গৃহস্থালী / রান্নাঘর ও ডাইনিং"),
    price: 750,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Mixing+Bowls+Cream",
        key: "dummy/prod-039-1.jpg",
        alt: i18n("Ceramic mixing bowl set of 3 in cream"),
        order: 0,
      },
    ],
    size: { type: "custom", custom: "14 cm / 18 cm / 22 cm diameter" },
    colorId: "color-cream",
    color: i18n("Cream", "ক্রিম"),
    ownerId: "owner-me",
    owner: "Saif",
    grade: "M",
    condition: "Excellent" as const,
    stock: 1,
    status: "ACTIVE" as const,
  },

  // ── Household > Home Decor ──
  {
    _id: "prod-040",
    sku: "TBD-HDE-001",
    slug: "woven-wall-tapestry-bohemian",
    title: i18n("Bohemian Woven Wall Tapestry", "বোহেমিয়ান উইভেন ওয়াল ট্যাপেস্ট্রি"),
    brand: "Artisan",
    categoryId: "cat-house-decor",
    categoryPath: i18n("Household / Home Decor", "গৃহস্থালী / হোম ডেকোর"),
    price: 680,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Wall+Tapestry",
        key: "dummy/prod-040-1.jpg",
        alt: i18n("Bohemian woven wall tapestry, multi-color"),
        order: 0,
      },
    ],
    size: { type: "custom", custom: "80 × 120 cm" },
    colorId: "color-mustard",
    color: i18n("Mustard", "সরিষে হলুদ"),
    ownerId: "owner-rahim",
    owner: "Rahim",
    grade: "B",
    condition: "Good" as const,
    stock: 1,
    status: "ACTIVE" as const,
  },

  // ── Household > Storage & Organization ──
  {
    _id: "prod-041",
    sku: "TBD-HST-001",
    slug: "fabric-storage-baskets-gray-set-of-2",
    title: i18n("Fabric Storage Baskets — Set of 2", "ফেব্রিক স্টোরেজ বাস্কেট — ২ পিস সেট"),
    brand: "Muji",
    categoryId: "cat-house-storage",
    categoryPath: i18n("Household / Storage & Organization", "গৃহস্থালী / স্টোরেজ ও সংগঠন"),
    price: 620,
    images: [
      {
        url: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Storage+Baskets+Gray",
        key: "dummy/prod-041-1.jpg",
        alt: i18n("Fabric storage baskets in gray, set of 2"),
        order: 0,
      },
    ],
    size: { type: "custom", custom: "30 × 25 × 20 cm each" },
    colorId: "color-gray",
    color: i18n("Gray", "ধূসর"),
    ownerId: "owner-me",
    owner: "Saif",
    grade: "O",
    condition: "Excellent" as const,
    notes: i18n("Collapsible. Reinforced handles."),
    stock: 1,
    status: "ACTIVE" as const,
  },
];

// ─── 5. Admin User ─────────────────────────────────────────────────────────
// Password is "admin123" (hashed with bcrypt, rounds=12).

export const users = [
  {
    _id: "user-admin",
    email: "admin@thriftedbd.com",
    passwordHash: "$2a$12$LJ3m4ys3Lk0TSwHnbfOMiOXPm1Qlq5GzGxBq8F5YKpLGh/hvV/N2e",
    role: "admin" as const,
  },
];

// ─── 6. Customer Accounts ──────────────────────────────────────────────────

export const customers = [
  {
    _id: "cust-001",
    email: "nusrat@gmail.com",
    name: "Nusrat Jahan",
    phone: "01712345678",
    passwordHash: "$2a$12$LJ3m4ys3Lk0TSwHnbfOMiOXPm1Qlq5GzGxBq8F5YKpLGh/hvV/N2e",
    addresses: [
      {
        label: "Home",
        address: "House 12, Road 5, Dhanmondi",
        city: "Dhaka",
        isDefault: true,
      },
    ],
    favoriteProductIds: ["prod-001", "prod-020"],
    emailVerified: null,
  },
  {
    _id: "cust-002",
    email: "tanvir@outlook.com",
    name: "Tanvir Ahmed",
    phone: "01798765432",
    passwordHash: "$2a$12$LJ3m4ys3Lk0TSwHnbfOMiOXPm1Qlq5GzGxBq8F5YKpLGh/hvV/N2e",
    addresses: [
      {
        label: "Office",
        address: "Uttara, Sector 7, Road 14",
        city: "Dhaka",
        isDefault: true,
      },
      {
        label: "Home",
        address: "Village: Joypur, Post: Bera",
        city: "Pabna",
        isDefault: false,
      },
    ],
    favoriteProductIds: ["prod-010"],
    emailVerified: null,
  },
  {
    _id: "cust-003",
    email: "farzana@yahoo.com",
    name: "Farzana Haque",
    phone: "01855556666",
    passwordHash: "$2a$12$LJ3m4ys3Lk0TSwHnbfOMiOXPm1Qlq5GzGxBq8F5YKpLGh/hvV/N2e",
    addresses: [
      {
        label: "Home",
        address: "GEC Circle, Chittagong",
        city: "Chittagong",
        isDefault: true,
      },
    ],
    favoriteProductIds: [],
    emailVerified: null,
  },
];

// ─── 7. Cart (guest, unconverted) ──────────────────────────────────────────

export const carts = [
  {
    _id: "cart-001",
    customerId: null,
    cartToken: "dummy-cart-token-abc123",
    items: [
      {
        productId: "prod-001",
        title: i18n("Nike Crewneck T-Shirt", "নাইকি ক্রুনেক টি-শার্ট"),
        price: 850,
        image: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Nike+Tee+Black",
        quantity: 1,
      },
      {
        productId: "prod-017",
        title: i18n("Zara Corset Top", "জারা কর্সেট টপ"),
        price: 890,
        image: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Zara+Corset+Black",
        quantity: 1,
      },
    ],
    contactEmail: "guest@example.com",
    contactPhone: null,
    lastActivityAt: new Date("2026-06-28T14:30:00Z"),
    convertedAt: null,
    convertedOrderId: null,
  },
];

// ─── 8. Orders ─────────────────────────────────────────────────────────────

export const orders = [
  {
    _id: "order-001",
    orderNumber: "TBD-20260701-001",
    items: [
      {
        productId: "prod-010",
        title: i18n("Champion Reverse Weave Hoodie", "চ্যাম্পিয়ন রিভার্স উইভ হুডি"),
        price: 1850,
        image: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Champion+Hoodie+Navy",
        quantity: 1,
        ownerId: "owner-me",
        ownerName: "Saif",
      },
    ],
    customerId: "cust-001",
    customer: {
      name: "Nusrat Jahan",
      phone: "01712345678",
      address: "House 12, Road 5, Dhanmondi",
      city: "Dhaka",
    },
    payment: {
      method: "COD" as const,
      status: "PAID" as const,
      collectedAt: new Date("2026-07-05T10:00:00Z"),
    },
    confirmationCall: {
      status: "CONFIRMED" as const,
      attempts: 1,
      calledAt: new Date("2026-07-01T16:00:00Z"),
      calledBy: "user-admin",
      notes: "Customer confirmed via phone.",
    },
    riskFlags: [],
    advancePayment: {
      required: false,
      status: "NOT_REQUIRED" as const,
    },
    orderStatus: "DELIVERED" as const,
    statusHistory: [
      { status: "PENDING" as const, changedAt: new Date("2026-07-01T14:00:00Z") },
      { status: "CONFIRMED" as const, changedAt: new Date("2026-07-01T16:00:00Z") },
      { status: "PACKED" as const, changedAt: new Date("2026-07-02T11:00:00Z") },
      { status: "SHIPPED" as const, changedAt: new Date("2026-07-02T17:00:00Z") },
      { status: "DELIVERED" as const, changedAt: new Date("2026-07-05T10:00:00Z") },
    ],
    courier: {
      provider: "Steadfast" as const,
      consignmentId: "STD-123456",
      trackingId: "TRK-ABCDE1",
      trackingUrl: "https://steadfast.com/track/TRK-ABCDE1",
      courierStatus: "delivered",
    },
    notificationsSent: {
      orderConfirmation: new Date("2026-07-01T16:05:00Z"),
      dispatchTracking: new Date("2026-07-02T17:10:00Z"),
      deliveryConfirmation: new Date("2026-07-05T10:05:00Z"),
    },
    shippingFee: 70,
    discountApplied: 0,
    total: 1920,
  },
  {
    _id: "order-002",
    orderNumber: "TBD-20260703-002",
    items: [
      {
        productId: "prod-005",
        title: i18n("Tommy Hilfiger Casual Shirt", "টমি হিলফিগার ক্যাজুয়াল শার্ট"),
        price: 1200,
        image: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Tommy+Shirt+Blue",
        quantity: 1,
        ownerId: "owner-shaikh",
        ownerName: "Shaikh",
      },
      {
        productId: "prod-025",
        title: i18n("H&M Wide Leg Linen Pants", "এইচএন্ডএম ওয়াইড লেগ লিনেন প্যান্ট"),
        price: 1150,
        image: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=HM+Linen+Pants",
        quantity: 1,
        ownerId: "owner-shaikh",
        ownerName: "Shaikh",
      },
    ],
    customerId: null,
    customer: {
      name: "Abdul Karim",
      phone: "01987654321",
      address: "Shop 5, New Market, Rajshahi",
      city: "Rajshahi",
    },
    payment: {
      method: "COD" as const,
      status: "PENDING" as const,
    },
    confirmationCall: {
      status: "UNREACHABLE" as const,
      attempts: 3,
      notes: "Called 3 times, no answer.",
    },
    riskFlags: ["UNCONFIRMED_ADDRESS"],
    advancePayment: {
      required: false,
      status: "NOT_REQUIRED" as const,
    },
    orderStatus: "PENDING" as const,
    statusHistory: [{ status: "PENDING" as const, changedAt: new Date("2026-07-03T12:00:00Z") }],
    courier: {
      provider: null,
    },
    notificationsSent: {},
    shippingFee: 130,
    discountApplied: 0,
    total: 2480,
  },
  {
    _id: "order-003",
    orderNumber: "TBD-20260620-003",
    items: [
      {
        productId: "prod-012",
        title: i18n("The North Face Nuptse Jacket", "দ্য নর্থ ফেস নাপসি জ্যাকেট"),
        price: 2800,
        image: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=TNF+Nuptse+Black",
        quantity: 1,
        ownerId: "owner-shaikh",
        ownerName: "Shaikh",
      },
    ],
    customerId: "cust-003",
    customer: {
      name: "Farzana Haque",
      phone: "01855556666",
      address: "GEC Circle, Chittagong",
      city: "Chittagong",
    },
    payment: {
      method: "bKash" as const,
      status: "PAID" as const,
      transactionRef: "bKash-8H9K2M1N",
      collectedAt: new Date("2026-06-20T15:30:00Z"),
    },
    confirmationCall: {
      status: "CONFIRMED" as const,
      attempts: 1,
      calledAt: new Date("2026-06-20T16:00:00Z"),
      calledBy: "user-admin",
    },
    riskFlags: ["LARGE_ORDER_NEW_BUYER"],
    advancePayment: {
      required: true,
      amount: 1400,
      status: "PAID" as const,
      transactionRef: "bKash-ADV-8H9K2M1N",
      requestedAt: new Date("2026-06-20T14:00:00Z"),
      paidAt: new Date("2026-06-20T15:00:00Z"),
    },
    orderStatus: "SHIPPED" as const,
    statusHistory: [
      { status: "PENDING" as const, changedAt: new Date("2026-06-20T13:00:00Z") },
      { status: "CONFIRMED" as const, changedAt: new Date("2026-06-20T16:00:00Z") },
      { status: "PACKED" as const, changedAt: new Date("2026-06-21T10:00:00Z") },
      { status: "SHIPPED" as const, changedAt: new Date("2026-06-22T14:00:00Z") },
    ],
    courier: {
      provider: "Pathao" as const,
      consignmentId: "PTH-789012",
      trackingId: "TRK-XYZ987",
      trackingUrl: "https://pathao.com/track/TRK-XYZ987",
      courierStatus: "in_transit",
    },
    notificationsSent: {
      orderConfirmation: new Date("2026-06-20T16:05:00Z"),
      dispatchTracking: new Date("2026-06-22T14:10:00Z"),
    },
    shippingFee: 130,
    discountApplied: 0,
    total: 2930,
  },
  {
    _id: "order-004",
    orderNumber: "TBD-20260615-004",
    items: [
      {
        productId: "prod-007",
        title: i18n("Levi's Checked Shirt", "লেভাইস চেক শার্ট"),
        price: 990,
        image: "https://placehold.co/600x800/e8ebe6/0e0f0c?text=Levis+Check+Red",
        quantity: 1,
        ownerId: "owner-rahim",
        ownerName: "Rahim",
      },
    ],
    customerId: null,
    customer: {
      name: "Masud Rana",
      phone: "01611112222",
      address: "2 no. Gate, Mymensingh Sadar",
      city: "Mymensingh",
    },
    payment: {
      method: "COD" as const,
      status: "COLLECTED" as const,
      transactionRef: "COD-collect-001",
      collectedAt: new Date("2026-06-22T12:00:00Z"),
    },
    confirmationCall: {
      status: "CONFIRMED" as const,
      attempts: 1,
      calledAt: new Date("2026-06-15T18:00:00Z"),
      calledBy: "user-admin",
    },
    riskFlags: [],
    advancePayment: {
      required: false,
      status: "NOT_REQUIRED" as const,
    },
    orderStatus: "CANCELLED" as const,
    statusHistory: [
      { status: "PENDING" as const, changedAt: new Date("2026-06-15T11:00:00Z") },
      { status: "CONFIRMED" as const, changedAt: new Date("2026-06-15T18:00:00Z") },
      { status: "PACKED" as const, changedAt: new Date("2026-06-16T09:00:00Z") },
      { status: "SHIPPED" as const, changedAt: new Date("2026-06-16T15:00:00Z") },
      { status: "DELIVERED" as const, changedAt: new Date("2026-06-22T12:00:00Z") },
      { status: "CANCELLED" as const, changedAt: new Date("2026-06-25T10:00:00Z") },
    ],
    cancelReason: "Customer returned — wrong size.",
    courier: {
      provider: "Steadfast" as const,
      consignmentId: "STD-234567",
      trackingId: "TRK-FGH456",
      courierStatus: "returned",
    },
    notificationsSent: {
      orderConfirmation: new Date("2026-06-15T18:05:00Z"),
      dispatchTracking: new Date("2026-06-16T15:10:00Z"),
      deliveryConfirmation: new Date("2026-06-22T12:05:00Z"),
    },
    shippingFee: 130,
    discountApplied: 0,
    total: 1120,
  },
];

// ─── 9. Settings (singleton) ───────────────────────────────────────────────

export const settings = {
  _id: "settings-singleton",
  deliveryFee: { insideDhaka: 70, outsideDhaka: 130 },
  storeContact: {
    phone: "01700000000",
    email: "hello@thriftedbd.com",
    address: "Dhaka, Bangladesh",
  },
  socialLinks: {
    facebook: "https://facebook.com/thriftedbd",
    instagram: "https://instagram.com/thriftedbd",
    tiktok: "https://tiktok.com/@thriftedbd",
    youtube: "https://youtube.com/@thriftedbd",
  },
  announcement: i18n(
    "📦 Free shipping on orders over 3000৳!",
    "📦 ৩০০০৳ এর অর্ডারে ফ্রি ডেলিভারি!",
  ),
  riskThresholds: { largeOrderAmount: 5000 },
  homepage: {
    heroSlides: [
      {
        imageUrl: "/banners/banner_guy_girl.jpeg",
        imageKey: "",
        headline: "Preloved, not less loved",
        subheadline:
          "Quality-checked imported thrift from Korea, Japan, Taiwan & China — delivered cash-on-delivery across Bangladesh.",
        ctaText: "Shop new in",
        ctaLink: "/products",
        order: 0,
        enabled: true,
      },
      {
        imageUrl: "/banners/banner_bags.jpeg",
        imageKey: "",
        headline: "Bags with a past",
        subheadline:
          "Totes, crossbodies and backpacks — one-of-a-kind thrifted finds, ready to carry.",
        ctaText: "Shop bags",
        ctaLink: "/products",
        order: 1,
        enabled: true,
      },
      {
        imageUrl: "/banners/banner_girl_tops.jpeg",
        imageKey: "",
        headline: "Tops that tell a story",
        subheadline:
          "Blouses, tees and knits for her — unique preloved pieces, freshly dropped every week.",
        ctaText: "Shop women's tops",
        ctaLink: "/products",
        order: 2,
        enabled: true,
      },
      {
        imageUrl: "/banners/banner_gents_tops.jpeg",
        imageKey: "",
        headline: "Sharp. Secondhand. Sorted.",
        subheadline:
          "Shirts and tees for him — imported thrift, quality-checked and priced to move.",
        ctaText: "Shop men's tops",
        ctaLink: "/products",
        order: 3,
        enabled: true,
      },
      {
        imageUrl: "/banners/banner_palazzo.jpeg",
        imageKey: "",
        headline: "Flow into palazzo season",
        subheadline: "Breezy wide-leg palazzos — thrifted, one-of-a-kind and made for Dhaka days.",
        ctaText: "Shop palazzos",
        ctaLink: "/products",
        order: 4,
        enabled: true,
      },
    ],
    featuredProductIds: ["prod-001", "prod-010", "prod-020", "prod-031"],
    featuredCategoryIds: ["cat-men-tshirt", "cat-women-dress", "cat-bag-backpack"],
    whyBuyBlocks: [
      {
        icon: "ShieldCheck",
        title: i18n("Quality Checked", "গুণগত মান যাচাইকৃত"),
        description: i18n(
          "Every item is inspected before listing.",
          "প্রতিটি পণ্য তালিকাভুক্তির পূর্বে পরীক্ষিত।",
        ),
      },
      {
        icon: "Truck",
        title: i18n("Fast Delivery", "দ্রুত ডেলিভারি"),
        description: i18n(
          "COD available all across Bangladesh.",
          "সারা বাংলাদেশে ক্যাশ অন ডেলিভারি।",
        ),
      },
      {
        icon: "Repeat",
        title: i18n("Easy Returns", "সহজ রিটার্ন"),
        description: i18n("Not happy? Return within 7 days.", "৭ দিনের মধ্যে রিটার্ন করুন।"),
      },
    ],
    faqs: [
      {
        question: i18n("What condition are the clothes in?", "পোশাকের অবস্থা কেমন?"),
        answer: i18n(
          "Each item is graded Excellent, Good, or Fair. We photograph and note every flaw.",
          "প্রতিটি আইটেম এক্সেলেন্ট, গুড বা ফেয়ার হিসেবে গ্রেড করা হয়।",
        ),
        order: 0,
      },
      {
        question: i18n("How does COD work?", "ক্যাশ অন ডেলিভারি কিভাবে কাজ করে?"),
        answer: i18n(
          "Pay when your order arrives. Delivery is 2–5 business days inside Dhaka, 5–7 days outside.",
          "অর্ডার হাতে পেয়ে পেমেন্ট করুন। ঢাকায় ২-৫ দিন, ঢাকার বাইরে ৫-৭ দিন।",
        ),
        order: 1,
      },
      {
        question: i18n("Can I return an item?", "পণ্য ফেরত দিতে পারবো?"),
        answer: i18n(
          "Yes, within 7 days of delivery if the item doesn't match the description. COD refund is processed after return pickup.",
          "হ্যাঁ, ডেলিভারির ৭ দিনের মধ্যে বিবরণের সাথে মিল না থাকলে ফেরত দিতে পারেন।",
        ),
        order: 2,
      },
    ],
  },
};

// ─── 10. Transactions (Cash Ledger) ────────────────────────────────────────

export const transactions = [
  {
    _id: "txn-001",
    type: "COD_REMITTANCE" as const,
    amount: 1920,
    method: "Cash" as const,
    reference: "COD-remit-JunWk1",
    orderIds: ["order-001"],
    courierProvider: "Steadfast" as const,
    status: "RECONCILED" as const,
    receivedAt: new Date("2026-07-06T12:00:00Z"),
    recordedBy: "user-admin",
    notes: "Weekly COD remittance from Steadfast.",
  },
  {
    _id: "txn-002",
    type: "ONLINE_PAYMENT" as const,
    amount: 2800,
    method: "bKash" as const,
    reference: "bKash-8H9K2M1N",
    orderIds: ["order-003"],
    status: "RECEIVED" as const,
    receivedAt: new Date("2026-06-20T15:30:00Z"),
    recordedBy: "user-admin",
    notes: "Full payment via bKash, order TBD-20260620-003.",
  },
  {
    _id: "txn-003",
    type: "ADVANCE_PAYMENT" as const,
    amount: 1400,
    method: "bKash" as const,
    reference: "bKash-ADV-8H9K2M1N",
    orderIds: ["order-003"],
    status: "RECEIVED" as const,
    receivedAt: new Date("2026-06-20T15:00:00Z"),
    recordedBy: "user-admin",
    notes: "Advance payment (50%) for NF Nuptse jacket.",
  },
  {
    _id: "txn-004",
    type: "COD_REMITTANCE" as const,
    amount: 990,
    method: "Cash" as const,
    reference: "COD-collect-001",
    orderIds: ["order-004"],
    courierProvider: "Steadfast" as const,
    status: "PENDING" as const,
    recordedBy: "user-admin",
    notes: "Awaiting remittance for returned order.",
  },
  {
    _id: "txn-005",
    type: "ONLINE_PAYMENT" as const,
    amount: 1200,
    method: "Nagad" as const,
    reference: "Nagad-X7Y8Z9",
    orderIds: [],
    status: "PENDING" as const,
    recordedBy: "user-admin",
    notes: "Pending — customer sent to wrong number. Sorting out.",
  },
];

// ─── 11. Blacklist ─────────────────────────────────────────────────────────

export const blacklist = [
  {
    _id: "bl-001",
    phone: "01912341234",
    name: "Shakib Khan",
    reason: "Refused COD delivery twice. Unreachable after order.",
    relatedOrderIds: [],
    isActive: true,
    addedBy: "user-admin",
  },
  {
    _id: "bl-002",
    phone: "01799998888",
    reason: "Failed delivery address — no such location. Order returned.",
    relatedOrderIds: [],
    isActive: true,
    addedBy: "user-admin",
  },
];

// ─── 12. Coupons ───────────────────────────────────────────────────────────

export const coupons = [
  {
    _id: "coup-001",
    code: "WELCOME10",
    discountType: "PERCENTAGE" as const,
    discountValue: 10,
    minOrderAmount: 1000,
    maxUses: 100,
    usedCount: 23,
    expiresAt: new Date("2026-12-31T23:59:59Z"),
    isActive: true,
  },
  {
    _id: "coup-002",
    code: "FLAT150",
    discountType: "FIXED_BDT" as const,
    discountValue: 150,
    minOrderAmount: 1500,
    maxUses: 50,
    usedCount: 8,
    expiresAt: new Date("2026-09-30T23:59:59Z"),
    isActive: true,
  },
  {
    _id: "coup-003",
    code: "FREESHIP",
    discountType: "PERCENTAGE" as const,
    discountValue: 0,
    minOrderAmount: 3000,
    maxUses: 200,
    usedCount: 5,
    expiresAt: new Date("2026-08-31T23:59:59Z"),
    isActive: true,
  },
  {
    _id: "coup-004",
    code: "EXPIRED50",
    discountType: "PERCENTAGE" as const,
    discountValue: 50,
    minOrderAmount: 2000,
    maxUses: 10,
    usedCount: 10,
    expiresAt: new Date("2025-12-31T23:59:59Z"),
    isActive: true,
  },
];

// ─── 13. Promotions ────────────────────────────────────────────────────────

export const promotions = [
  {
    _id: "promo-001",
    type: "top-bar" as const,
    pages: ["global" as const],
    title: "Free Shipping Announcement",
    headline: i18n("🎉 Free shipping on orders over 3000৳", "🎉 ৩০০০৳ এর অর্ডারে ফ্রি শিপিং"),
    body: undefined,
    ctaText: undefined,
    ctaLink: undefined,
    backgroundColor: "#0e0f0c",
    activeFrom: new Date("2026-06-01T00:00:00Z"),
    activeTo: new Date("2026-08-31T23:59:59Z"),
    enabled: true,
    order: 0,
  },
  {
    _id: "promo-002",
    type: "section" as const,
    pages: ["homepage" as const],
    title: "Summer Sale Banner",
    headline: i18n("Summer Sale — Up to 40% Off", "সামার সেল — ৪০% পর্যন্ত ছাড়"),
    body: i18n(
      "Grab the best pre-loved summer styles before they're gone.",
      "সবচেয়ে ভালো প্রি-লাভড সামার স্টাইলগুলি শেষ হওয়ার আগে নিয়ে নিন।",
    ),
    imageUrl: "https://placehold.co/1200x400/e2f6d5/0e0f0c?text=Summer+Sale",
    imageKey: "dummy/summer-sale-banner.jpg",
    ctaText: i18n("Shop Sale", "সেল দেখুন"),
    ctaLink: "/products?sort=sale",
    backgroundColor: "#e2f6d5",
    activeFrom: new Date("2026-06-15T00:00:00Z"),
    activeTo: new Date("2026-07-31T23:59:59Z"),
    enabled: true,
    order: 1,
  },
  {
    _id: "promo-003",
    type: "offer-card" as const,
    pages: ["pdp" as const, "cart" as const],
    title: "Bundle Offer",
    headline: i18n("Buy 2, Get 5% Off", "২টি কিনলে ৫% ছাড়"),
    body: i18n(
      "Add another item to your order and save!",
      "আপনার অর্ডারে আরেকটি আইটেম যোগ করুন এবং বাঁচান!",
    ),
    ctaText: i18n("Browse More", "আরও দেখুন"),
    ctaLink: "/products",
    backgroundColor: "#e8ebe6",
    activeFrom: new Date("2026-06-01T00:00:00Z"),
    activeTo: new Date("2026-12-31T23:59:59Z"),
    enabled: true,
    order: 2,
  },
];

// ─── 14. Newsletter Subscribers ────────────────────────────────────────────

export const subscribers = [
  { email: "nusrat@gmail.com", isActive: true },
  { email: "tanvir@outlook.com", isActive: true },
  { email: "bounced@invalid.com", isActive: false },
  { email: "farzana@yahoo.com", isActive: true },
];
